Vagrant.configure(2) do |config|
	config.vm.box = "Ubuntu16"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "6000"
	end
	config.vm.provision :shell, privileged: false, :path => "provision.sh"
end
